services:
  multiagent-rag:
    build: .
    container_name: multiagent_rag_app
    volumes:
      - .:/app
    working_dir: /app
    command: >
      jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.disable_check_xsrf=True --no-browser
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    ports:
      - "8888:8888"
